# Generated by Django 4.1.2 on 2022-10-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_to_one_room',
            name='group_name',
            field=models.CharField(default='mygroup', max_length=20),
        ),
        migrations.AlterField(
            model_name='personal_messages',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.one_to_one_room'),
        ),
    ]
