# Generated by Django 4.1.2 on 2022-10-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group_or_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
