# Generated by Django 4.1.2 on 2022-10-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_notification_user_notification_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group_or_contact',
        ),
    ]
