# Generated by Django 4.1.2 on 2022-10-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_remove_notification_group_or_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagess', to='home.group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_to',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
